### ISSUE TITLE
Release for Foxy (API freeze)

### ISSUE THREAD

**Issue by jacobperron** [ros2/tinydir_vendor#16]
We should release `tinydir_vendor` into Foxy so we can start building this package and it's downstream dependencies on build.ros2.org. Note, this doesn't have to be the final version of the package for Foxy.

**Comment by dirk-thomas** [comment]
Are there actually any packages left using this?

**Comment by jacobperron** [comment]
> Are there actually any packages left using this?

I guess not. I thought rcl did, based on this page: http://repo.ros2.org/status_page/blocked_releases_foxy.html?q=label%3D%22UNBLOCKED_BLOCKING%22&s=6&r=1

But I see the dependency was removed since Eloquent.

I'll close this since it doesn't look like we need it.

Perhaps we should consider removing it from [ros2.repos](https://github.com/ros2/ros2/blob/master/ros2.repos).

**Comment by dirk-thomas** [comment]
> Perhaps we should consider removing it from ros2.repos.


ros2/ros2#887
