### ISSUE TITLE
Issue in installation of the "ARGoS epuck-plugin"..?

### ISSUE THREAD

**Issue by kashif-hub** [ros2/tinydir_vendor#20]
how to overcome the issue in the installation of the ARGoS-epuck plugin which is shown in snapshot.
![image](https://user-images.githubusercontent.com/84039991/118401234-54d03d80-b67e-11eb-9e2a-98f7f5565131.png)

**Comment by emersonknapp** [comment]
This question doesn't seem to be related to `tinydir_vendor` - and appears to be a general usage question - can you please ask it on https://answers.ros.org/questions/ ?

A couple notes:
* it is easier for somebody to help you if you copy-paste your output into a code block - it's easier to search and read than a screenshot of a terminal. This is general advice, not specific to ROS.
* You don't generally build your ROS 2 workspace by invoking `cmake` directly. You probably want to use `colcon` - see https://docs.ros.org/en/foxy/Tutorials/Colcon-Tutorial.html for some more information
