### ISSUE TITLE
Declared license mismatch Apache 2, Amazon proprietary, 2 Clause BSD

### ISSUE THREAD

**Issue by tfoote** [ros2/tinydir_vendor#7]
The contents of the NOTICE https://github.com/ros2/tinydir_vendor/blob/607fa785024557a756e60eae21b4dc9706136f81/NOTICE#L2 say 

`Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved. `
Which is incongruous with the rest of the package indicators. 

The Apache 2 license was added here: e1d493330635bb0ee837742f2adb183e52be0953

Then this notice: 30c6932d361dc22adc901e504e3a9393503c7274

However looking a little bit deeper the license for tinydir looks to actually be the 2 clause BSD https://github.com/cxong/tinydir/blob/master/COPYING which we should reflect in the package.xml since the actual code being delivered by this package is the tinydir code. 

@hyandell Please check this is an valid analysis and update it.

**Comment by AAlon** [comment]
Addressed by https://github.com/ros2/tinydir_vendor/pull/8. Thanks Tully.

**Comment by chapulina** [comment]
It looks like the changes made on #8 don't match the pattern of other vendor packages, where the `LICENSE` file corresponds to the contents of the vendor package, and there's an extra line on `package.xml` mentioning the license of the original package. See for example:

* [console_bridge_vendor](https://github.com/ros2/console_bridge_vendor)
* [spdlog_vendor](https://github.com/ros2/spdlog_vendor)

**Comment by Blast545** [comment]
@chapulina @tfoote @AAlon Please see #12
